### ISSUE TITLE
rpc.get_next_blockvalidators() tries to process deprecated return result

### ISSUE THREAD

**Issue by Devel484** [CityOfZion/neo-mamba#222]
The method `get_next_blockvalidators()` tries to [parse](https://github.com/CityOfZion/neo-mamba/blob/5bc73174f91f6c2466743fbeb53f55dfb35786da/neo3/api/noderpc.py#L40) an deprecated JSON structure. The field `active` is no longer available.

See [NeoRPC V3.4.0](https://github.com/neo-project/neo-modules/blob/7db1c7956ac68758793a6ea30b5329cceb6ab1bc/src/RpcServer/RpcServer.Blockchain.cs#L209-L221).

**Comment by ixje** [comment]
Thanks for reporting. I've pushed a fix
