### ISSUE TITLE
Reason for requiring Python 3.10 for neo-mamba?

### ISSUE THREAD

**Issue by vvarg229** [CityOfZion/neo-mamba#258]
Hello,

We are currently using neo-mamba to test NeoFS and have noticed that it requires Python 3.10.* as per the following link:
https://github.com/CityOfZion/neo-mamba/blob/master/setup.cfg#L26

Our testing servers run on Python 3.9, and we would like to understand the reasoning behind the use of Python 3.10. Are there any specific features or performance improvements that led to this decision?

Additionally, would it be possible to run neo-mamba using Python 3.9, or are there known compatibility issues that we should be aware of?

Thank you in advance for your assistance.

**Comment by roman-khimov** [comment]
We're running Debian stable and it's still 3.9, but well, it can be handled and maybe bookworm will be released soon anyway.

**Comment by ixje** [comment]
[pyenv](https://github.com/pyenv/pyenv#install-additional-python-versions) might be of help to easily install a Python version from source
