### ISSUE TITLE
Mamba v0.4 Marketing Banner

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-mamba#43]
This issue covers the creation of the marketing banner for v0.4.

@ixje could you please provide a few bullets of key features?

FYI @J-G-W

**Comment by ixje** [comment]
* Native smart contract support (NEP-5 and others)
* Generic smart contract execution support

It's kind of hard to break it down into smaller pieces than this. It's a huge update, but it all falls under these 2 points. If it  works out as planned before the release I might be able to add
* Blockchain helper class for supporting node like capabilities

The latter basically means that you can take the existing network syncing helper classes, combine them with the blockchain helper class to form a basic node that will collect all the blocks, process them and persist them in the select storage format.

**Comment by J-G-W** [comment]
@ixje @lllwvlvwlll  Let me know when the final copy has been decided and I'll amend and send the final artwork.
![image](https://user-images.githubusercontent.com/36457062/100260282-241a1180-2f41-11eb-9919-0eb0da9a1c23.png)
