### ISSUE TITLE
Account creation using NEP-2

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#60]
Create a single account using NEP-2 (password is needed)

[NewAccount()](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/account.go#L89-L95)
[NewAccountFromEncryptedKey(nep2: string, password: string)](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/account.go#L177-L187)
[NewAccountFromPrivateKey()](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/account.go#L218-L235)

**Comment by meevee98** [comment]
**Summary or problem description**
Account creation is not using the method proposed on NEP-2.

**Do you have any solution you want to propose?**
Account creation should follow the standardized passphrase-protected private key format. This requirement should cover the private key generation and encryption steps detailed [here.](https://github.com/neo-project/proposals/blob/master/nep-2.mediawiki#encryption-steps)

**Additional contextual information**

- In Neo, the account is the smart contract and the address represents a contract script. The below flow diagram shows how to derive the public key from the private key and then to the address:
https://docs.neo.org/v3/docs/en-us/basic/concept/wallets.html#accounts
