### ISSUE TITLE
Decrypting NEP-2 account

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#61]

**Comment by meevee98** [comment]
**Summary or problem description**
On issue #XXX, we're covering account encryption using NEP-2. On this issue, we need to decrypt it following the same neo proposal.

**Do you have any solution you want to propose?**
We need to follow the steps bellow to implement account decrypting using [NEP-2](https://github.com/neo-project/proposals/blob/master/nep-2.mediawiki#decryption-steps).

The decrypt implementation can also be seen here (https://github.com/neo-project/neo/blob/master/src/neo/Wallets/Wallet.cs), in the "Decodes a private key from the specified NEP-2 string " section.

**Additional contextual information**
- Depends on #60
