### ISSUE TITLE
Single Account Signing

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#66]
**Summary or problem description**
There's currently no support to single account signing in Neo Mamba (?)

**Do you have any solution you want to propose?**

https://docs.neo.org/v3/docs/en-us/basic/concept/transaction.html
https://docs.neo.org/v3/docs/en-us/basic/concept/cryptography/encryption_algorithm.html (?)

**Additional contextual information**
Sign a transaction using a single account

[SignTx(magic: Magic, tx: Transaction)
GetVerificationScript()](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/account.go#L98-L130)

**Comment by ixje** [comment]
Done in  `feature-wallet` branch
