### ISSUE TITLE
Multi Account Signing

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#67]
**Summary or problem description**
There's not support for multi account signing, where the funds are associate with a smart contract and not a single user. That way, the transactions of the funds in this type of multi account can only be executed if N of X people provides signatures for it. For example, 2 out of 3 of the account owners must sign in order for the funds to be withdrawn.

**Do you have any solution you want to propose?**

We should follow implement multi accounts signing as is described [here]

**Additional contextual information**
Add support to multisign

[ConvertMultisig(m int, publicKeys : publicKey[])](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/account.go#L190-L215)

**Comment by ixje** [comment]
done in feature-branch
