### ISSUE TITLE
Wallet - make contract invocation

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#76]
~~We should be able to send a transaction that will invoke a smart contract, with parameters, from the account API.
Example:
`account.invoke(GAS.script_hash, "transfer", from, to, amount, user_data)`
There should be a way to run the transaction on 'read mode' only (test invoke), before sending it to the network.~~

@ixje we need to talk to you about this. Should this be on the Account class or in another place? We need to be able to 'test-invoke' the invocation first and we don't know where this logic should go.

**Comment by ixje** [comment]
It would be nice to have some description so I understand what the purpose of this is and why it is associated to wallet. Is it creating and signing a transaction that does a contract invocation? Or does it do a test invocation against the local chain with a specific account from the wallet?

Same for #77

**Comment by ixje** [comment]
@lock9 please elaborate why you see a need to test invoke. If it is to determine the fees, then I will take care of that in #88 . If it is for another reason, please elaborate.

**Comment by lock9** [comment]
Hi @ixje, like I said on slack, I think we need some way to run the transaction locally to view its outcome before sending it to the network.

**Comment by ixje** [comment]
Not a wallet feature. Running a TX can be done by instantiating the ApplicationEngine with the necessary data.
