### ISSUE TITLE
Wallet - Make Transfer

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo-mamba#77]

**Comment by ixje** [comment]
from discord
> Stanislav_nspcc — 04/22/2021
Yes, that's creating NEP-17 token transfer TX and relaying it

I plan to add an example to the `/examples/` folder which shows how to manually build a multi-signature transaction which withdraws the funds from the genesis blocks (which is nothing more but calling "transfer neo" from the consensus multisig address)

**Comment by ixje** [comment]
done
